DROP TABLE IF EXISTS SORDER;

CREATE TABLE SORDER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  quantity INT NOT NULL,
  customer_id INT NOT NULL,
  item_name VARCHAR(250) DEFAULT NULL,
  total_cost INT NOT NULL
);